/* YumCheck 음식 DB (AI 없는 버전)
 * - ALLERGENS: 사용자가 고를 수 있는 알러지 항목
 * - RELIGIONS / DIETS: 종교·식이 제한과 그 규칙
 * - INGREDIENTS: 재료 사전 (tags = 알러지/카테고리)
 * - FOODS: 음식 20개. ingredients = 주재료, hidden = 흔히 들어가지만 눈에 안 보이는 재료
 * 나중에 서버(DB)로 옮길 때 이 구조 그대로 테이블로 만들면 됩니다.
 */

const ALLERGENS = [
  { id: 'peanut',    emoji: '🥜', ko: '땅콩',          en: 'Peanuts' },
  { id: 'treenut',   emoji: '🌰', ko: '견과류',        en: 'Tree nuts' },
  { id: 'milk',      emoji: '🥛', ko: '우유·유제품',   en: 'Milk / Dairy' },
  { id: 'egg',       emoji: '🥚', ko: '달걀',          en: 'Eggs' },
  { id: 'wheat',     emoji: '🌾', ko: '밀(글루텐)',    en: 'Wheat / Gluten' },
  { id: 'soy',       emoji: '🫘', ko: '대두(콩)',      en: 'Soy' },
  { id: 'fish',      emoji: '🐟', ko: '생선',          en: 'Fish' },
  { id: 'shellfish', emoji: '🦐', ko: '갑각류·조개류', en: 'Shellfish' },
  { id: 'sesame',    emoji: '⚪', ko: '참깨',          en: 'Sesame' },
];

// danger = 먹으면 안 됨(빨강), caution = 확인 필요(주황)
const RELIGIONS = [
  { id: 'none',     emoji: '➖', ko: '해당 없음', en: 'None', danger: [], caution: [] },
  { id: 'islam',    emoji: '☪️', ko: '이슬람교 (할랄)', en: 'Islam (Halal)',
    danger: ['pork', 'alcohol'], caution: ['beef', 'chicken'],
    noteKo: '돼지고기·알코올 금지, 다른 고기는 할랄 인증 확인 필요',
    noteEn: 'No pork or alcohol; other meat must be halal' },
  { id: 'judaism',  emoji: '✡️', ko: '유대교 (코셔)', en: 'Judaism (Kosher)',
    danger: ['pork', 'shellfish'], caution: ['beef', 'chicken'],
    noteKo: '돼지고기·갑각류 금지, 다른 고기는 코셔 확인 필요',
    noteEn: 'No pork or shellfish; other meat must be kosher' },
  { id: 'hinduism', emoji: '🕉️', ko: '힌두교', en: 'Hinduism',
    danger: ['beef'], caution: [],
    noteKo: '소고기 금지', noteEn: 'No beef' },
  { id: 'buddhism', emoji: '☸️', ko: '불교', en: 'Buddhism',
    danger: [], caution: ['pork', 'beef', 'chicken', 'fish', 'shellfish'],
    noteKo: '육식을 피하는 경우가 많음', noteEn: 'Many avoid meat and fish' },
  { id: 'christianity', emoji: '✝️', ko: '기독교', en: 'Christianity', danger: [], caution: [],
    noteKo: '일반적인 음식 제한 없음', noteEn: 'No general food restrictions' },
];

const DIETS = [
  { id: 'vegetarian', emoji: '🥬', ko: '채식 (베지테리언)', en: 'Vegetarian',
    danger: ['pork', 'beef', 'chicken', 'fish', 'shellfish'] },
  { id: 'vegan', emoji: '🌱', ko: '비건', en: 'Vegan',
    danger: ['pork', 'beef', 'chicken', 'fish', 'shellfish', 'egg', 'milk'] },
];

// 태그에 쓰이는 카테고리 이름 (알러지 외)
const CATEGORY_LABELS = {
  pork:    { ko: '돼지고기', en: 'Pork' },
  beef:    { ko: '소고기',   en: 'Beef' },
  chicken: { ko: '닭고기',   en: 'Chicken' },
  alcohol: { ko: '알코올',   en: 'Alcohol' },
};

const INGREDIENTS = {
  kimchi:         { ko: '김치',           en: 'Kimchi',            tags: [] },
  pork:           { ko: '돼지고기',       en: 'Pork',              tags: ['pork'] },
  pork_belly:     { ko: '삼겹살(돼지고기)', en: 'Pork belly',      tags: ['pork'] },
  ham:            { ko: '햄',             en: 'Ham',               tags: ['pork'] },
  bacon:          { ko: '베이컨',         en: 'Bacon',             tags: ['pork'] },
  lard:           { ko: '라드(돼지기름)', en: 'Lard (pork fat)',   tags: ['pork'] },
  pepperoni:      { ko: '페퍼로니',       en: 'Pepperoni',         tags: ['pork', 'beef'] },
  beef:           { ko: '소고기',         en: 'Beef',              tags: ['beef'] },
  beef_patty:     { ko: '소고기 패티',    en: 'Beef patty',        tags: ['beef'] },
  chicken:        { ko: '닭고기',         en: 'Chicken',           tags: ['chicken'] },
  tofu:           { ko: '두부',           en: 'Tofu',              tags: ['soy'] },
  green_onion:    { ko: '대파',           en: 'Green onion',       tags: [] },
  gochugaru:      { ko: '고춧가루',       en: 'Chili flakes',      tags: [] },
  fish_sauce:     { ko: '액젓(멸치)',     en: 'Fish sauce',        tags: ['fish'] },
  salted_shrimp:  { ko: '새우젓',         en: 'Salted shrimp',     tags: ['shellfish'] },
  anchovy_broth:  { ko: '멸치 육수',      en: 'Anchovy broth',     tags: ['fish'] },
  anchovy:        { ko: '안초비',         en: 'Anchovy',           tags: ['fish'] },
  garlic:         { ko: '마늘',           en: 'Garlic',            tags: [] },
  rice:           { ko: '밥',             en: 'Rice',              tags: [] },
  egg:            { ko: '달걀',           en: 'Egg',               tags: ['egg'] },
  spinach:        { ko: '시금치',         en: 'Spinach',           tags: [] },
  bean_sprouts:   { ko: '콩나물·숙주',    en: 'Bean sprouts',      tags: [] },
  carrot:         { ko: '당근',           en: 'Carrot',            tags: [] },
  gochujang:      { ko: '고추장',         en: 'Gochujang',         tags: ['wheat', 'soy'] },
  sesame_oil:     { ko: '참기름',         en: 'Sesame oil',        tags: ['sesame'] },
  sesame_seeds:   { ko: '통깨',           en: 'Sesame seeds',      tags: ['sesame'] },
  soy_sauce:      { ko: '간장',           en: 'Soy sauce',         tags: ['soy', 'wheat'] },
  onion:          { ko: '양파',           en: 'Onion',             tags: [] },
  pear:           { ko: '배',             en: 'Asian pear',        tags: [] },
  rice_cake:      { ko: '떡',             en: 'Rice cake',         tags: [] },
  fish_cake:      { ko: '어묵',           en: 'Fish cake',         tags: ['fish', 'wheat'] },
  seaweed:        { ko: '김',             en: 'Seaweed',           tags: [] },
  pickled_radish: { ko: '단무지',         en: 'Pickled radish',    tags: [] },
  doenjang:       { ko: '된장',           en: 'Soybean paste',     tags: ['soy'] },
  zucchini:       { ko: '애호박',         en: 'Zucchini',          tags: [] },
  potato:         { ko: '감자',           en: 'Potato',            tags: [] },
  clams:          { ko: '조개',           en: 'Clams',             tags: ['shellfish'] },
  glass_noodles:  { ko: '당면',           en: 'Glass noodles',     tags: [] },
  lettuce:        { ko: '상추',           en: 'Lettuce',           tags: [] },
  ssamjang:       { ko: '쌈장',           en: 'Ssamjang',          tags: ['soy', 'wheat', 'sesame'] },
  wheat_noodles:  { ko: '밀면',           en: 'Wheat noodles',     tags: ['wheat'] },
  chunjang:       { ko: '춘장',           en: 'Black bean paste',  tags: ['soy', 'wheat'] },
  cabbage:        { ko: '양배추',         en: 'Cabbage',           tags: [] },
  oyster_sauce:   { ko: '굴소스',         en: 'Oyster sauce',      tags: ['shellfish', 'soy', 'wheat'] },
  flour:          { ko: '밀가루',         en: 'Wheat flour',       tags: ['wheat'] },
  squid:          { ko: '오징어',         en: 'Squid',             tags: ['shellfish'] },
  shrimp:         { ko: '새우',           en: 'Shrimp',            tags: ['shellfish'] },
  burger_bun:     { ko: '햄버거 빵',      en: 'Burger bun',        tags: ['wheat'] },
  cheese:         { ko: '치즈',           en: 'Cheese',            tags: ['milk'] },
  tomato:         { ko: '토마토',         en: 'Tomato',            tags: [] },
  pickles:        { ko: '피클',           en: 'Pickles',           tags: [] },
  ketchup:        { ko: '케첩',           en: 'Ketchup',           tags: [] },
  mayonnaise:     { ko: '마요네즈',       en: 'Mayonnaise',        tags: ['egg'] },
  butter:         { ko: '버터',           en: 'Butter',            tags: ['milk'] },
  pizza_dough:    { ko: '피자 도우',      en: 'Pizza dough',       tags: ['wheat'] },
  mozzarella:     { ko: '모짜렐라 치즈',  en: 'Mozzarella',        tags: ['milk'] },
  tomato_sauce:   { ko: '토마토 소스',    en: 'Tomato sauce',      tags: [] },
  olive_oil:      { ko: '올리브유',       en: 'Olive oil',         tags: [] },
  flour_tortilla: { ko: '밀 토르티야',    en: 'Flour tortilla',    tags: ['wheat'] },
  beans:          { ko: '콩(리프라이드 빈)', en: 'Beans',          tags: [] },
  sour_cream:     { ko: '사워크림',       en: 'Sour cream',        tags: ['milk'] },
  salsa:          { ko: '살사',           en: 'Salsa',             tags: [] },
  pasta:          { ko: '파스타면',       en: 'Pasta',             tags: ['wheat'] },
  basil:          { ko: '바질',           en: 'Basil',             tags: [] },
  pine_nuts:      { ko: '잣',             en: 'Pine nuts',         tags: ['treenut'] },
  parmesan:       { ko: '파르메산 치즈',  en: 'Parmesan',          tags: ['milk'] },
  romaine:        { ko: '로메인',         en: 'Romaine lettuce',   tags: [] },
  croutons:       { ko: '크루통',         en: 'Croutons',          tags: ['wheat'] },
  caesar_dressing:{ ko: '시저 드레싱',    en: 'Caesar dressing',   tags: ['egg', 'milk'] },
  rice_noodles:   { ko: '쌀국수면',       en: 'Rice noodles',      tags: [] },
  peanuts:        { ko: '땅콩',           en: 'Peanuts',           tags: ['peanut'] },
  peanut_oil:     { ko: '땅콩기름',       en: 'Peanut oil',        tags: ['peanut'] },
  buttermilk:     { ko: '버터밀크',       en: 'Buttermilk',        tags: ['milk'] },
  cream:          { ko: '크림',           en: 'Cream',             tags: ['milk'] },
  milk:           { ko: '우유',           en: 'Milk',              tags: ['milk'] },
  white_wine:     { ko: '화이트 와인',    en: 'White wine',        tags: ['alcohol'] },
  maple_syrup:    { ko: '메이플 시럽',    en: 'Maple syrup',       tags: [] },
  imitation_crab: { ko: '게맛살',         en: 'Imitation crab',    tags: ['fish', 'wheat', 'egg', 'shellfish'] },
  avocado:        { ko: '아보카도',       en: 'Avocado',           tags: [] },
  cucumber:       { ko: '오이',           en: 'Cucumber',          tags: [] },
  mirin:          { ko: '미림(맛술)',     en: 'Mirin (rice wine)', tags: ['alcohol'] },
  tobiko:         { ko: '날치알',         en: 'Flying fish roe',   tags: ['fish'] },
};

const FOODS = [
  // ── 한식 ──
  { id: 'kimchi_jjigae', cat: 'korean', emoji: '🍲', ko: '김치찌개', en: 'Kimchi Stew',
    aliases: ['kimchi jjigae', 'kimchi stew'],
    ingredients: ['kimchi', 'pork', 'tofu', 'green_onion', 'gochugaru', 'garlic'],
    hidden: ['fish_sauce', 'salted_shrimp', 'anchovy_broth'] },
  { id: 'bibimbap', cat: 'korean', emoji: '🍚', ko: '비빔밥', en: 'Bibimbap',
    aliases: ['bibimbab', 'mixed rice'],
    ingredients: ['rice', 'beef', 'egg', 'spinach', 'bean_sprouts', 'carrot', 'gochujang', 'sesame_oil'],
    hidden: ['soy_sauce', 'sesame_seeds'] },
  { id: 'bulgogi', cat: 'korean', emoji: '🥩', ko: '불고기', en: 'Bulgogi',
    aliases: ['korean bbq beef', 'marinated beef'],
    ingredients: ['beef', 'soy_sauce', 'onion', 'green_onion', 'pear', 'garlic', 'sesame_oil'],
    hidden: ['sesame_seeds'] },
  { id: 'tteokbokki', cat: 'korean', emoji: '🌶️', ko: '떡볶이', en: 'Tteokbokki',
    aliases: ['spicy rice cake', 'topokki', 'ddeokbokki'],
    ingredients: ['rice_cake', 'gochujang', 'fish_cake', 'green_onion', 'egg'],
    hidden: ['anchovy_broth', 'soy_sauce'] },
  { id: 'gimbap', cat: 'korean', emoji: '🍙', ko: '김밥', en: 'Gimbap',
    aliases: ['kimbap', 'korean rice roll'],
    ingredients: ['rice', 'seaweed', 'egg', 'ham', 'pickled_radish', 'carrot', 'spinach', 'sesame_oil'],
    hidden: ['fish_cake', 'sesame_seeds'] },
  { id: 'doenjang_jjigae', cat: 'korean', emoji: '🥘', ko: '된장찌개', en: 'Soybean Paste Stew',
    aliases: ['doenjang jjigae', 'bean paste stew'],
    ingredients: ['doenjang', 'tofu', 'zucchini', 'potato', 'onion', 'green_onion'],
    hidden: ['anchovy_broth', 'clams', 'beef'] },
  { id: 'japchae', cat: 'korean', emoji: '🍜', ko: '잡채', en: 'Japchae',
    aliases: ['glass noodle stir fry', 'chapchae'],
    ingredients: ['glass_noodles', 'beef', 'spinach', 'carrot', 'onion', 'soy_sauce', 'sesame_oil'],
    hidden: ['egg', 'sesame_seeds'] },
  { id: 'samgyeopsal', cat: 'korean', emoji: '🥓', ko: '삼겹살', en: 'Grilled Pork Belly',
    aliases: ['samgyupsal', 'pork belly', 'korean bbq'],
    ingredients: ['pork_belly', 'lettuce', 'garlic', 'kimchi', 'ssamjang'],
    hidden: ['sesame_oil', 'fish_sauce'] },
  { id: 'jjajangmyeon', cat: 'korean', emoji: '🍝', ko: '짜장면', en: 'Black Bean Noodles',
    aliases: ['jajangmyeon', 'jjajang', 'black bean noodle'],
    ingredients: ['wheat_noodles', 'chunjang', 'pork', 'onion', 'cabbage', 'potato'],
    hidden: ['oyster_sauce'] },
  { id: 'haemul_pajeon', cat: 'korean', emoji: '🥞', ko: '해물파전', en: 'Seafood Pancake',
    aliases: ['pajeon', 'seafood scallion pancake', 'korean pancake'],
    ingredients: ['flour', 'green_onion', 'squid', 'shrimp', 'egg'],
    hidden: ['soy_sauce', 'clams'] },

  // ── 양식/미국 외식 ──
  { id: 'cheeseburger', cat: 'western', emoji: '🍔', ko: '치즈버거', en: 'Cheeseburger',
    aliases: ['burger', 'hamburger', '햄버거'],
    ingredients: ['burger_bun', 'beef_patty', 'cheese', 'lettuce', 'tomato', 'pickles', 'ketchup'],
    hidden: ['sesame_seeds', 'mayonnaise', 'butter'] },
  { id: 'pepperoni_pizza', cat: 'western', emoji: '🍕', ko: '페퍼로니 피자', en: 'Pepperoni Pizza',
    aliases: ['pizza', '피자'],
    ingredients: ['pizza_dough', 'mozzarella', 'tomato_sauce', 'pepperoni'],
    hidden: ['olive_oil', 'parmesan'] },
  { id: 'chicken_burrito', cat: 'western', emoji: '🌯', ko: '치킨 부리토', en: 'Chicken Burrito',
    aliases: ['burrito', '부리또'],
    ingredients: ['flour_tortilla', 'chicken', 'rice', 'beans', 'cheese', 'sour_cream', 'salsa'],
    hidden: ['lard'] },
  { id: 'pesto_pasta', cat: 'western', emoji: '🍝', ko: '페스토 파스타', en: 'Pesto Pasta',
    aliases: ['pesto', 'basil pasta', '파스타'],
    ingredients: ['pasta', 'basil', 'pine_nuts', 'parmesan', 'olive_oil', 'garlic'],
    hidden: ['egg', 'butter'] },
  { id: 'caesar_salad', cat: 'western', emoji: '🥗', ko: '시저 샐러드', en: 'Caesar Salad',
    aliases: ['salad', '샐러드', 'caesar'],
    ingredients: ['romaine', 'croutons', 'parmesan', 'caesar_dressing'],
    hidden: ['anchovy', 'bacon'] },
  { id: 'pad_thai', cat: 'western', emoji: '🍜', ko: '팟타이', en: 'Pad Thai',
    aliases: ['phad thai', 'thai noodles'],
    ingredients: ['rice_noodles', 'shrimp', 'egg', 'tofu', 'bean_sprouts', 'peanuts', 'fish_sauce'],
    hidden: ['oyster_sauce', 'chicken'] },
  { id: 'fried_chicken', cat: 'western', emoji: '🍗', ko: '프라이드 치킨', en: 'Fried Chicken',
    aliases: ['chicken', '치킨', 'southern fried chicken'],
    ingredients: ['chicken', 'flour', 'buttermilk', 'egg'],
    hidden: ['peanut_oil'] },
  { id: 'clam_chowder', cat: 'western', emoji: '🥣', ko: '클램 차우더', en: 'Clam Chowder',
    aliases: ['chowder', 'new england clam chowder', '수프'],
    ingredients: ['clams', 'potato', 'cream', 'bacon', 'onion', 'flour'],
    hidden: ['butter', 'white_wine'] },
  { id: 'pancakes', cat: 'western', emoji: '🥞', ko: '팬케이크', en: 'Pancakes',
    aliases: ['pancake', 'hotcakes', '핫케이크'],
    ingredients: ['flour', 'milk', 'egg', 'butter', 'maple_syrup'],
    hidden: ['buttermilk'] },
  { id: 'california_roll', cat: 'western', emoji: '🍣', ko: '캘리포니아 롤', en: 'California Roll',
    aliases: ['sushi', 'sushi roll', '스시', '초밥'],
    ingredients: ['rice', 'imitation_crab', 'avocado', 'cucumber', 'seaweed', 'mayonnaise'],
    hidden: ['sesame_seeds', 'tobiko', 'mirin', 'soy_sauce'] },
];
